# Generated by Django 5.0.2 on 2024-03-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': ' کاربر', 'verbose_name_plural': ' کاربران'},
        ),
    ]
