# Generated by Django 5.0.2 on 2024-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
