# Generated by Django 5.0.2 on 2024-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
