# Generated by Django 5.0.2 on 2024-03-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_senderinfo_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senderinfo',
            options={'verbose_name': 'اطلاعات ارسال', 'verbose_name_plural': 'اطلاعات ارسال'},
        ),
        migrations.AddField(
            model_name='senderinfo',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='کد پستی'),
        ),
    ]
