# Generated by Django 5.0.2 on 2024-03-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_senderinfo_options_senderinfo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='کد پستی'),
        ),
    ]
